### ISSUE TITLE
Issue while opening the Sorting Function (MAC OS)

### ISSUE THREAD

**Issue by designpixel** [jonpecar/qrCodeImageSorterGUI#6] opened 2022-12-05 09:34 UTC
Hi all, I have an issue when I'm opening the Sorting function. Please see below the output in the console.

launched
Exception in Tkinter callback
Traceback (most recent call last):
File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/init.py", line 1921, in call
return self.func(*args)
File "/usr/local/lib/python3.10/site-packages/customtkinter/windows/widgets/ctk_button.py", line 527, in _clicked
self._command()
File "/Users/chris/Downloads/qrCodeImageSorterGUI-0.2.0/qrImageIndexerGUI/launch_window.py", line 21, in click_sort_button
ScanImagesWindow(self)
File "/Users/chris/Downloads/qrCodeImageSorterGUI-0.2.0/qrImageIndexerGUI/sort_images_window.py", line 62, in init
self.image_grid = ImageGrid(self)
File "/Users/chris/Downloads/qrCodeImageSorterGUI-0.2.0/qrImageIndexerGUI/sort_images_window.py", line 182, in init
self.vscrollbar = ctk.CTkScrollbar(self)
File "/usr/local/lib/python3.10/site-packages/customtkinter/windows/widgets/ctk_scrollbar.py", line 52, in init
self._button_color = ThemeManager.theme["CTkScrollbar"]["scrollbar_color"] if button_color is None else self._check_color_type(button_color)
KeyError: 'scrollbar_color'

Please let me know if you need more details from somewhere... :)

Best regards,
Christian

**Comment by designpixel** [comment] 2022-12-06 08:34
Hi again, Just thinking - is the issue located in the color of the scrollbar as mentioned in the KeyError Statement and make it sense to check this value? Or is the issue located somewhere else...?
I would be more than happy if we can finde the issue, cause this tool is really great and important for me if this should would work... :)

Can you please help me again to find the solution? 

Many thanks in advance...!
Chris

**Comment by jonpecar** [comment] 2022-12-06 09:19
I believe the issue is related to the CustomTkinter package I am using to try and provide a more modern looking interface. If I had to guess it is for some reason misbehaving on Mac OS. I am going to have to try and see if I can get the issue to replicate on Linux and maybe find a workaround or fix it in the underlying framework.

There is also a large update due in the underlying library that may help with the issue.

In the meantime you could try installing version 0.1.2: https://pypi.org/project/qrImageIndexerGUI/0.1.2/

The only difference was changing to the more modern UI so you will not loose any features.
________________________________

**Comment by designpixel** [comment] 2022-12-06 09:39
OK - cool. Than I try to install this and see how it works. The Look and feel is not important for me... :) Thanks Christian

**Comment by designpixel** [comment] 2022-12-06 15:20
Hi - It's me again. First of all, sorry for this long ping pong on issues I have and Thanks very much for you support.

The next issue I have is, that the Images will not be sorted with the QR codes. I create the PDF File expl.:

Set1
   Christian
Set2
   Meike

...

The I make Pics with the QR Code for Christian and with the QR for Meike etc. The I Klick for sorting and choose at the end the target folder, but the Images are not sorted in the Folders for Christian & Meike. They are totally mixed.

What do I do wrong here in this set?

I have already checked your Video and several configs, but always the same.

Thanks again for your help.

Best whishes & and a great Santa Claus Day :)
Christian

**Comment by jonpecar** [comment] 2022-12-11 00:21
Hi Christian, I am not sure what is happening. Do you get different results when sorting the same photo set? or are they different photo sets? I couldn't comment on what is happening without seeing the photos themselves.

**Comment by jonpecar** [comment] 2022-12-11 04:22
Please also note that there is now a version 0.2.1 which uses the latest version of CustomTkinter. This may resolve the initial issue you were having, but I cannot make any guarantees.

**Comment by jonpecar** [comment] 2023-03-26 06:22
As I am unable to reproduce and there has been no further feedback I am closing this issue as unresolved.

**Closed** 2023-03-26 06:22 UTC
